name: flutter_nexmuv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uno: ^1.1.9
  intl: ^0.19.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  fl_chart: ^0.66.0
  animated_icon_button: ^1.0.2
  get_it: ^7.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
